name: Release (Windows)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (CMake, VS 2022, x64)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build (Release)
        run: cmake --build build --config Release --target gav_gif

      - name: Prepare artifact
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Copy-Item build/Release/gav_gif.exe dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gav_gif-windows
          path: dist/*

      - name: Create GitHub Release and upload exe
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/gav_gif.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


